--SELECT country FROM country
--WHERE country LIKE 'A%a';
--WHERE country LIKE '_____n';
--SELECT * FROM film
--WHERE title ILIKE '%t%t%t%t%';
--WHERE title LIKE 'C%' AND length > 90 AND rental_rate = 2.99;